version: '3.9'
services:
  nginx:
    image: nginx-i
    container_name: ${NGINX_HOST}
    profiles: ["hls"]
    build:
      context: nginx
      dockerfile: Dockerfile
      args:
        ENABLED_MODULES: rtmp
    env_file: .env
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${RTMP_PORT}:${RTMP_PORT}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/rtmp.conf:/etc/nginx/templates/rtmp.conf.template
      - ./nginx/http.conf:/etc/nginx/templates/http.conf.template
      - ./nginx/index.html:/usr/share/nginx/html/index.html


  tunnel:
    container_name: cloudflared-tunnel
    profiles: ["hls"]
    image: cloudflare/cloudflared:latest
    restart: always
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --protocol http2 run
    depends_on:
      - nginx

  rtsp-server:
    image: bluenviron/mediamtx:1.16.1
    container_name: rtsp-tcp-server
    profiles: ["rtsp"]
    ports:
      - ${RTSP_PORT}:${RTSP_PORT} # RTSP Port
      - ${RTMP_PORT}:${RTMP_PORT} # RTMP (if needed)
      - ${HTTP_STANDARD_PORT}:${INTERNAL_HLS_PORT} # HLS
    restart: always